Support negative integers
tkriik/erlang-fizzbuzz pull request #1
Opened 2018-10-23 11:07 UTC by firoxer

Hi,

here's a proposed implementation for supporting negative integers.

I noticed that `up_to` wouldn't sound good anymore when it's certain that the input will be negative, so I aliased `up_to` to `up_from` for those cases. This makes the usage look like `fizzbuzz:up_to(123). fizzbuzz:up_from(-123).`. I hope this is fine.

2018-10-23 12:33 UTC, tkriik requested changes
Quality stuff, thanks for the contribution. However, I propose the following change to the module API:

 * Implement a new function `to`, that goes either up or down, depending on the sign of the given number.

Since this new function is more generic, we should deprecate the old `up_to` -function by adding the following line above the function declaration:

`-deprecated({up_to, 1})`

This is to ensure that any projects depending on the old function have ample time to migrate away to the better and more versatile concurrent non-deterministic Fibonacci function, `to`.

2018-11-01 18:28 UTC, firoxer commented
Deprecating `up_to/1` is a GOOD idea. However, my Erlang compiler couldn't understand `-deprecated` so I used `%% @deprecated` instead. I hope this is okay.

The rest of the requested changes are provided as requested.

2018-12-10 08:53 UTC, tkriik commented
> Deprecating `up_to/1` is a GOOD idea. However, my Erlang compiler couldn't understand `-deprecated` so I used `%% @deprecated` instead. I hope this is okay.

This is not okay at all, since the users of this module are not going to read the source code for deprecation warnings. Add this line under the top `-module(...)` definition:

```
-deprecated({up_to, 1}).
```

which should work, and if not, then fix your Erlang compiler.

2018-12-10 09:02 UTC, firoxer commented
Turns out the compiler did not work because I forgot the period

2018-12-17 12:39 UTC, tkriik commented on fizzbuzz.erl
> +%% @deprecated Please use {@link fizzbuzz:to/1} instead.
```suggestion
```

2018-12-17 12:41 UTC, tkriik requested changes
One final suggestion, after which this is ready to be merged.

2018-12-17 12:45 UTC, tkriik approved these changes
Looks good to me now. Thank you for contributing to open source!

2018-12-17 12:45 UTC, merged